
<b>[예제]</b>

boston 데이터로  LinearRegression을 사용하여 선형 회귀분석을 실시한 후, 추정된 회귀모형에 대해 해석하라

In [4]:
import pandas as pd 
import numpy as np 
import mglearn
X,y = mglearn.datasets.load_extended_boston()

In [5]:
X

array([[0.00000000e+00, 1.80000000e-01, 6.78152493e-02, ...,
        1.00000000e+00, 8.96799117e-02, 8.04248656e-03],
       [2.35922539e-04, 0.00000000e+00, 2.42302053e-01, ...,
        1.00000000e+00, 2.04470199e-01, 4.18080621e-02],
       [2.35697744e-04, 0.00000000e+00, 2.42302053e-01, ...,
        9.79579831e-01, 6.28144504e-02, 4.02790570e-03],
       ...,
       [6.11892474e-04, 0.00000000e+00, 4.20454545e-01, ...,
        1.00000000e+00, 1.07891832e-01, 1.16406475e-02],
       [1.16072990e-03, 0.00000000e+00, 4.20454545e-01, ...,
        9.82676920e-01, 1.29930407e-01, 1.71795127e-02],
       [4.61841693e-04, 0.00000000e+00, 4.20454545e-01, ...,
        1.00000000e+00, 1.69701987e-01, 2.87987643e-02]])

In [6]:
print(X.shape)
print(y.shape)

(506, 104)
(506,)


In [7]:
# 훈련, 테스트 셋 분리 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [8]:
print(X_train.shape)
print(y_train.shape)

(354, 104)
(354,)


In [9]:
#pip install sklearn
from sklearn.linear_model import LinearRegression
lr = LinearRegression() # 회귀모델 생성
lr.fit(X_train, y_train) # 회귀모델 학습 

LinearRegression()

In [10]:
# 기울기와 절편은 따로 호출하여 확인할 수 있다
print('기울기 :', lr.coef_)
print('절편 :', lr.intercept_)

기울기 : [-4.33704714e+02 -4.27754308e+01 -1.28481468e+02 -1.18776033e+01
 -1.78703730e+01  2.59686895e+01  5.63747064e+01 -5.58439243e+01
  1.61598828e+01  4.16901656e+01 -1.09516095e+01 -1.40253594e+01
 -2.19041413e+01  1.90551463e+01  2.76667699e+03  1.53047514e+03
  1.21268554e+02 -4.60499609e+00  2.48383118e+01 -3.00570284e+01
  9.59771262e+01  1.33888720e+03 -2.33427571e+03  2.61342693e+02
 -1.41712353e+00  3.20215615e+01 -1.45894092e+01 -2.10437385e+01
 -7.66545703e+00 -8.03876611e+01  8.62968881e+00  7.28471754e+00
 -1.10266163e+00 -2.24144700e+00  3.23407788e+01 -1.03736502e+01
  5.97750174e+01 -1.83399865e+01  3.64204995e+01 -4.26367054e+00
  1.59044619e+01  5.69081378e+01  1.48746227e+01  6.39295382e+01
 -2.16980861e+01  2.25591789e+01 -1.49418510e+01  5.49066542e+01
 -1.30858038e+01 -1.18776033e+01 -1.67729835e+01 -3.46890006e+01
  6.55871187e+00 -7.06931008e+00  1.15762091e+01 -5.82484408e+00
 -1.09660567e+01  5.89367073e+01 -1.93606085e+01  1.08440448e+00
  2.92079323e+01 -1

In [11]:
# 추정된 값을 보기 위해서는 모델.predict(x)를 출력한다

y_pred= lr.predict(X_test)
y_pred

array([ 23.91238964,  26.78414909,  30.01687048,  10.28605728,
        19.97437885,  19.70947018,  22.10807185,  20.49301402,
        12.11793241,  18.12056132,   7.28234863,  13.19064552,
        14.19307564,   8.31574685,  48.8118262 ,  35.6478669 ,
        23.59219392,  37.17322394,  32.23444089,  22.3010062 ,
        24.91200988,  21.49172813,  21.02418627,  27.58758607,
        17.95275344,  31.04267493,  16.28500244,  18.19156248,
        34.4580386 ,  13.81558423,  16.44667748,  18.32919563,
        19.63292289,  19.28759264,  26.33813933,  15.78458235,
         6.48085359,  36.57816588,  16.80284058,  13.60511103,
        22.48815769,  19.55024704,  19.42809998,  18.91401826,
        10.04053426,  22.16499085,  17.95419741,   9.34413112,
        12.54607347,  23.14172559, -28.22156936,  25.48915028,
        20.14824028,  53.32403243,   6.98809351,  21.23712406,
        16.86681946,  17.30122537,  17.98451255,  19.93228314,
        24.09199817,  21.30079299,  33.30990714,  29.13

In [12]:
# 잔차를 확인하는 방법 : y값과 추정값의 차를 계산

resid= y_test - y_pred
resid

array([ -1.31238964,  23.21585091,  -7.01687048,  -1.98605728,
         1.22562115,   0.19052982,  -1.50807185,  -1.79301402,
         3.98206759,   0.47943868,   1.51765137,   4.00935448,
         0.70692436,   2.18425315,   1.1881738 ,  -6.6478669 ,
        -0.59219392,  -3.87322394,  -2.83444089,  -1.3010062 ,
        -1.11200988,  -2.39172813,  -0.62418627,   1.51241393,
         1.34724656,  -7.94267493,   3.31499756,   1.20843752,
         4.2419614 ,   4.88441577,  -1.84667748,   1.67080437,
         0.86707711,   0.81240736,  -2.73813933,   1.01541765,
        -0.88085359,  13.42183412,  -2.30284058,  -0.30511103,
         1.41184231,   0.44975296,   0.37190002,  -5.11401826,
         6.45946574,  -0.56499085,   2.34580259,   7.65586888,
        -0.74607347,   4.35827441,  43.82156936,  -2.38915028,
         4.15175972, -10.52403243,   8.61190649,   0.46287594,
         0.23318054,  -0.10122537,  -2.98451255,   1.76771686,
        -5.49199817,  -0.30079299,  -0.20990714,   2.36

In [13]:
## R2 
print("훈련 데이터 셋 성능 : ", lr.score(X_train,y_train))
print("테스트 데이터 셋 성능 : ", lr.score(X_test,y_test))

훈련 데이터 셋 성능 :  0.9517246762476054
테스트 데이터 셋 성능 :  0.6486839499987773


In [14]:
#mse 
(resid**2).sum()/len(y_test)

29.25250713919926

In [12]:
## rmse 
np.sqrt((resid**2).sum()/len(y_test))

5.408558693330346

In [13]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print(mse)
print(rmse)

29.25250713919926
5.408558693330346


- R2 값이 훈련데이터에 비해 테스트 데이터셋이 더 작으므로 과대적합임을 알 수 있다.  
- R2 값이 0.648은 좋은 성능은 아니다. 
- 모델의 성능을 높이려면, 과대적합을 조정해주어야 함 

In [14]:
X_train

array([[0.01823449, 0.        , 0.78555718, ..., 1.        , 0.901766  ,
        0.81318193],
       [0.00121704, 0.2       , 0.23826979, ..., 0.99024028, 0.16475301,
        0.02741108],
       [0.00619828, 0.        , 0.78555718, ..., 0.98878546, 0.41789074,
        0.17661331],
       ...,
       [0.00162594, 0.        , 0.35007331, ..., 0.98798327, 0.23505388,
        0.05592233],
       [0.0025059 , 0.        , 0.23643695, ..., 0.97913066, 0.46608557,
        0.22186595],
       [0.00149286, 0.        , 0.13159824, ..., 1.        , 0.35761589,
        0.12788913]])

In [15]:
### 다중공선성의 문제 있을 수 있다. 

from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_list = []
for i in range(X_train.shape[1]): 
    vif_list.append([variance_inflation_factor(X_train,i)])
vif_list


C:\Users\jjang\anaconda3\envs\ADP_Class\lib\site-packages\statsmodels\stats\outliers_influence.py:193: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)


[[54851.95197767613],
 [7130.307358208186],
 [22374.003679026846],
 [inf],
 [6771.725195571671],
 [6800.801502806481],
 [10940.386138579546],
 [7326.440153114255],
 [30805.61103699408],
 [81206.29682014103],
 [10708.631478254902],
 [7673.09915025527],
 [2412.5310782263655],
 [37.29568591935402],
 [19.417800952621043],
 [325173.70523822005],
 [14.822542635807283],
 [515.0122621388858],
 [177.6698962626534],
 [844.5913175230344],
 [30.361263840820758],
 [992617.8325887014],
 [2331396.8718411014],
 [29863.383191795456],
 [44.5538239375616],
 [159.09454435610166],
 [102.57528989122348],
 [13.509943115758212],
 [6.940197261396818],
 [50.240661897464726],
 [418.7975220112337],
 [44.137292535255966],
 [171.74257241835312],
 [28.918759686656628],
 [38.43267370061432],
 [63.36677850173572],
 [5720.689018922408],
 [28.167527476576897],
 [976.1444457223474],
 [159.60310031467287],
 [4324.919106210621],
 [1405.2563175684206],
 [1312.8887738668022],
 [236.1472746520232],
 [15955.742728721658],
 [20

In [16]:
vif_dt = pd.DataFrame(vif_list,columns=['vif'])

In [17]:
vif_dt[vif_dt['vif']<10]

vif
28  6.940197